### ISSUE TITLE
Highlighting the king's suqare

### ISSUE THREAD

**Issue by Priyanshiagarwal2006** [Navneet1206/Ether-Chess-OTC#10]
Hii @Navneet1206 
Highlighting the king's square when it is in check and also add multiple options of colours for player so that they can choose by their on choice. I’m confident I can resolve this and contribute to improving the user experience.

Thank You!

**Comment by Navneet1206** [comment]
Hi @Priyanshiagarwal2006 ,

Thanks for the suggestion! Highlighting the king’s square when it is in check is definitely a great idea, and adding multiple color options for the player to choose from would enhance the user experience. While I am currently focusing on the core functionality of the Pawn promotion, especially in Online Mode, I will consider these enhancements for future updates.

Appreciate your input and look forward to your contributions!

Best regards,
Navneet Vishwakarma
