### ISSUE TITLE
Redesign Site Color Scheme and Visual Aesthetics 

### ISSUE THREAD

**Issue by yashvisharma1204** [Navneet1206/Ether-Chess-OTC#13]
The overall visual aesthetics and color scheme of the website could be improved to create a more modern, cohesive, and visually appealing design. This issue aims to revamp the entire site’s color palette, typography, and layout to ensure a better user experience, accessibility, and a polished, professional look.

**Expected Outcome:**
- A modernized, visually appealing website with an updated, cohesive color scheme.
- Improved typography for better readability and a more professional look.
- Enhanced user experience across both desktop and mobile devices.
- Increased accessibility, making the site more usable for a wider range of users.

Design inspiration: 
<img width="943" alt="image" src="https://github.com/user-attachments/assets/0e3cb8a8-e140-407c-88ce-05fe27b7fb20" />

Further changes:
- Dark and Light mode

**Comment by Navneet1206** [comment]
Hi @yashvisharma1204 ,

Thank you for bringing this up! I really appreciate your suggestion and the detailed breakdown of the expected outcome. The design inspiration and proposed improvements are excellent and align well with the project’s goals.

I’ve assigned this issue to you. Feel free to start contributing, and don’t hesitate to reach out if you need any guidance or assistance during the process. Looking forward to seeing the amazing updates you bring to the website!

Best regards,
Navneet

**Comment by Navneet1206** [comment]
Hi @yashvisharma1204 ,

Thank you again for your contributions and interest in improving the project! If you haven’t already, it would mean a lot if you could *star* ✨the repository to show your support. It helps the project gain visibility and motivates contributors like you to keep up the great work!

Looking forward to collaborating more. 😊

Best regards,
Navneet

**Comment by yashvisharma1204** [comment]
> Hi @yashvisharma1204 ,
> 
> Thank you for bringing this up! I really appreciate your suggestion and the detailed breakdown of the expected outcome. The design inspiration and proposed improvements are excellent and align well with the project’s goals.
> 
> I’ve assigned this issue to you. Feel free to start contributing, and don’t hesitate to reach out if you need any guidance or assistance during the process. Looking forward to seeing the amazing updates you bring to the website!
> 
> Best regards, Navneet

Thank you for assigning!
I have created a pull request addressing this issue (#13). It includes updates to the interfaces for Home, Bot, and Free Mode. Please review the changes and let me know if there are any adjustments needed. Thank you!

**Comment by Navneet1206** [comment]
Hi @yashvisharma1204,

Thank you for your excellent work on this! Since the necessary changes have been successfully implemented and reviewed, I’m going to close this issue now.

There are still two pages left for the UI changes:

- Online Mode/Tournament Mode
- Leaderboard Page
Feel free to continue applying the updates to these pages whenever you're ready. If you need any assistance or encounter any challenges, don’t hesitate to reach out.

Great job, and thanks again for your contributions! 😊

Best regards,
Navneet

**Comment by yashvisharma1204** [comment]
Hey! Are you allotting points for pr?
