### ISSUE TITLE
Add dark and light mode theme toggle for website

### ISSUE THREAD

**Issue by Aditi2k5** [Navneet1206/Ether-Chess-OTC#2]

**Comment by Navneet1206** [comment]
Hi @Aditi2k5,

Thank you for suggesting the addition of a dark and light mode theme toggle for the website. While the primary focus of the project has been on core functionality, I agree that implementing a theme toggle would enhance the overall user experience by offering a more personalized and accessible interface.

I appreciate your initiative in proposing this feature. I am assigning this issue so everyone can proceed with the implementation. Please ensure the following:

1. The theme toggle should:
   - Be easily accessible on all pages of the website.
   - Provide a seamless transition between dark and light modes.
2. Ensure consistency in design and functionality across both themes.
3. Store user preferences (e.g., via local storage) so the selected theme persists across sessions.
4. Test thoroughly to confirm compatibility across different devices and browsers.

Looking forward to seeing your implementation! Let me know if you need any clarification or support during the process.

Best regards,  
Navneet Vishwakarma

**Comment by Balaji-R-2007** [comment]
> Hi @Aditi2k5,
> 
> Thank you for suggesting the addition of a dark and light mode theme toggle for the website. While the primary focus of the project has been on core functionality, I agree that implementing a theme toggle would enhance the overall user experience by offering a more personalized and accessible interface.
> 
> I appreciate your initiative in proposing this feature. I am assigning this issue so everyone can proceed with the implementation. Please ensure the following:
> 
>     1. The theme toggle should:
>        
>        * Be easily accessible on all pages of the website.
>        * Provide a seamless transition between dark and light modes.
> 
>     2. Ensure consistency in design and functionality across both themes.
> 
>     3. Store user preferences (e.g., via local storage) so the selected theme persists across sessions.
> 
>     4. Test thoroughly to confirm compatibility across different devices and browsers.
> 
> 
> Looking forward to seeing your implementation! Let me know if you need any clarification or support during the process.
> 
> Best regards, Navneet Vishwakarma

hi navaneet i can do that assign me to that

**Comment by Aditi2k5** [comment]
> Hi @Aditi2k5,
> 
> Thank you for suggesting the addition of a dark and light mode theme toggle for the website. While the primary focus of the project has been on core functionality, I agree that implementing a theme toggle would enhance the overall user experience by offering a more personalized and accessible interface.
> 
> I appreciate your initiative in proposing this feature. I am assigning this issue so everyone can proceed with the implementation. Please ensure the following:
> 
> 1. The theme toggle should:
>    
>    * Be easily accessible on all pages of the website.
>    * Provide a seamless transition between dark and light modes.
> 2. Ensure consistency in design and functionality across both themes.
> 3. Store user preferences (e.g., via local storage) so the selected theme persists across sessions.
> 4. Test thoroughly to confirm compatibility across different devices and browsers.
> 
> Looking forward to seeing your implementation! Let me know if you need any clarification or support during the process.
> 
> Best regards, Navneet Vishwakarma

@Navneet1206 can I be assigned to the issue? since I'm doing this as a part of swoc as well it shall be done from 1st onwards

**Comment by Navneet1206** [comment]
Hi @Balaji-R-20007 and @Aditi2k5 ,  

Thank you both for showing interest in working on this issue. After reviewing your profiles, I have decided to assign this task to **@Aditi2k5**, as their experience aligns well with the requirements of the project.  

**@Aditi2k5**, please proceed with the implementation as discussed. If you encounter any challenges or need clarification, feel free to reach out.  

**@Balaji-R-2007**, I appreciate your willingness to contribute and will keep you in mind for upcoming issues where your expertise can be utilized effectively. Stay tuned!  

Best regards,  
Navneet Vishwakarma

**Comment by Navneet1206** [comment]
Hi @Aditi2k5 and @Balaji-R-2007,  

Thank you for your suggestions and enthusiasm for contributing to this project. After further consideration, I have decided not to proceed with implementing a dark and light mode theme toggle at this time.  

The reason for this decision is that introducing a theme switcher impacts the entire project structure and functionality, which is currently focused on delivering core features. Maintaining consistency and simplicity across the project is a priority.  

I appreciate your understanding and look forward to your contributions to other issues that align better with the project goals.  

Best regards,  
Navneet Vishwakarma
